name: CI routine

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]


jobs:
  Estrutura:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.10"

    - name: Tests
      run: |
        cd app
        python3.12 -m unittest tests.test_classes
